# Generated by Django 2.2.2 on 2019-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='faw_type',
            new_name='fav_type',
        ),
        migrations.AddField(
            model_name='userask',
            name='course_name',
            field=models.CharField(default=1, max_length=50, verbose_name='课程名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
    ]
